# Generated by Django 3.1 on 2023-09-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('P_id', models.AutoField(primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=50, null=True)),
                ('Category', models.CharField(max_length=40, null=True)),
                ('P_quantity', models.CharField(max_length=5, null=True)),
                ('P_details', models.TextField(max_length=150, null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('P_image', models.ImageField(upload_to='photos/products')),
            ],
        ),
    ]
