# Generated by Django 5.1.2 on 2025-01-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230909_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='P_details',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
