# Generated by Django 3.1 on 2023-09-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='exp_month',
            field=models.CharField(max_length=10),
        ),
    ]
