# Generated by Django 3.1 on 2023-09-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20230922_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
