# Generated by Django 3.1 on 2023-09-05 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('F_id', models.AutoField(primary_key=True, serialize=False)),
                ('Services', models.CharField(max_length=10)),
                ('Comment', models.TextField(max_length=150)),
                ('Email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userdetails', to_field='Email_id')),
            ],
        ),
    ]
