# Generated by Django 3.1 on 2023-09-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('Admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('AdminName', models.CharField(max_length=40)),
                ('Email_id', models.EmailField(max_length=40, unique=True)),
                ('Password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
