# Generated by Django 3.1 on 2023-09-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminaccount',
            table='admins',
        ),
    ]
