# Generated by Django 3.1 on 2023-09-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20230926_0026'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminaccount',
            table='adminss',
        ),
    ]
