# Generated by Django 3.1 on 2023-09-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20230926_0034'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminaccount',
            table='admins',
        ),
    ]
