# Generated by Django 3.1 on 2023-09-22 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('pres_id', models.AutoField(primary_key=True, serialize=False)),
                ('pres_image', models.ImageField(upload_to='prescriptions/')),
                ('Email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='Email_id')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
    ]
