# Generated by Django 3.1 on 2023-09-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=20)),
                ('Mobile', models.IntegerField()),
                ('Email_id', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
