# Generated by Django 3.1 on 2023-09-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Mobile',
            field=models.IntegerField(default='15'),
        ),
        migrations.AlterModelTable(
            name='userdetails',
            table='userdetails',
        ),
    ]
