# Generated by Django 3.1 on 2023-09-09 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20230907_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='is_staff',
        ),
    ]
