# Generated by Django 3.1 on 2023-09-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20230925_1456'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetails',
            table='userdetail',
        ),
    ]
