# Generated by Django 3.1 on 2023-09-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_userdetails_is_staff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetails',
            table='userdetails',
        ),
    ]
