# Generated by Django 3.1 on 2023-09-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20230925_1458'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetails',
            table='userdetails',
        ),
    ]
