# Generated by Django 3.1 on 2023-09-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20230909_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
