# Generated by Django 3.1 on 2023-09-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20230925_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
