# Generated by Django 3.1 on 2023-09-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_userdetails_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Mobile',
            field=models.IntegerField(null=True),
        ),
    ]
