# Generated by Django 3.1 on 2023-09-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20230909_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='cart_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
