# Generated by Django 3.1 on 2023-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20230911_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='cart_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
