# Generated by Django 3.1 on 2023-09-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20230911_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='p_image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='p_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='p_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
