# Generated by Django 3.1 on 2023-09-22 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20230909_1637'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shipp_address', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('order_date', models.DateTimeField(max_length=30)),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('pay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
