# Generated by Django 3.1 on 2023-09-25 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20230925_1459'),
        ('order', '0003_auto_20230923_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userdetails', to_field='Email_id'),
        ),
    ]
